[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
 from = "https://jhackshaw.netlify.com/*"
 to = "https://jhackshaw.com/:splat"
 status = 301
 force = true
